language: python
python:
  - 3.6

sudo: required

services:
  - docker

install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - poetry install

script:
  - poetry run pytest
  - poetry run pylint foliant

deploy:
  provider: script
  script: poetry publish --build --username "$PYPI_USERNAME" --password "$PYPI_PASSWORD"
  on:
    tags: true

after_deploy:
  - git clone https://github.com/foliant-docs/docker.git
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - cd docker
  - docker build -t foliant/foliant:slim -t foliant/foliant:$TRAVIS_TAG-slim --build-arg VERSION=$TRAVIS_TAG -f Dockerfile-slim .
  - docker push foliant/foliant:slim
  - docker push foliant/foliant:$TRAVIS_TAG-slim
  - docker build -t foliant/foliant -t foliant/foliant:$TRAVIS_TAG .
  - docker push foliant/foliant
  - docker push foliant/foliant:$TRAVIS_TAG
  - docker build -t foliant/foliant:pandoc -t foliant/foliant:$TRAVIS_TAG-pandoc -f Dockerfile-pandoc .
  - docker push foliant/foliant:pandoc
  - docker push foliant/foliant:$TRAVIS_TAG-pandoc
